development:
  sessions:
    default:
      database: pugwarriors_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: pugwarriors_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:    
      database: pugwarriors_production
      hosts:            
        - localhost:27017
